language: ruby
rvm:
- 2.1

before_script:
- chmod +x ./script/cibuild

script:
- bundle exec jekyll build
- bundle exec htmlproof ./_site --only-4xx --check-favicon --check-html

branches:
    only:
    - gh-pages

env:
    global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true