# Metadata
title: "Ian Lai"
description: "Words from an autodidact, full-stack web developer (minus mobile development) who is currently based in London."
url: "https://www.fyianlai.com"
analytics_id: "UA-5243796-6"
disqus: "ianlai"
twitter: MrSaints

# Social media
social:
    behance: "https://www.behance.net/MrSaints"
    dribbble: "https://dribbble.com/MrSaints"
    github: "https://github.com/MrSaints"
    twitter: "https://twitter.com/MrSaints"

# Site config
defaults:
    - scope:
        path: ""
      values:
        layout: "default"
        thumbnail: "/img/thumb.jpg"
    - scope:
        path: ""
        type: "posts"
      values:
        author: "Ian Lai"
        is_post: true
excerpt_separator: <!--more-->

# Pagination
paginate: 5
paginate_path: "/page/:num/"
permalink: /:year/:month/:title/

gems:
    - jekyll-redirect-from
exclude:
    - CNAME
    - Gemfile
    - Rakefile
    - bower.json
    - gulpfile.js
    - package.json
    - bower_components/
    - node_modules/
    - sass/