defaults:
    - scope:
        path: ""
      values:
        layout: "default"
        thumbnail: "/img/thumb.jpg"
    - scope:
        path: ""
        type: "posts"
      values:
        author: "Ian Lai"
        is_post: true
        layout: "single"
excerpt_separator: <!--more-->
exclude:
    - CNAME
    - Gruntfile.coffee
    - bower.json
    - package.json
    - bower_components/
    - node_modules/
paginate: 5
paginate_path: "/page/:num/"
permalink: /:year/:month/:title/
sass:
    style: :compressed
analytics_id: "UA-5243796-6"
title: "Ian Lai"
description: "Words from an autodidact, full-stack web developer (minus mobile development) who is currently based in London."
url: "https://www.fyianlai.com"
social:
    disqus: "ianlai"
    behance: "https://www.behance.net/MrSaints"
    dribbble: "https://dribbble.com/MrSaints"
    github: "https://github.com/MrSaints"
    twitter: "https://twitter.com/MrSaints"
gems:
    - jekyll-redirect-from