defaults:
    - scope:
        path: ""
      values:
        layout: "default"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "single"
excerpt_separator: <!--more-->
exclude:
    - CNAME
    - Gruntfile.coffee
    - bower.json
    - package.json
#    - bower_components/
    - node_modules/
paginate: 5
paginate_path: "/page/:num/"
permalink: /:year/:month/:title
analytics_id: "UA-5243796-6"
title: "Ian Lai"
social:
    behance: "https://www.behance.net/MrSaints"
    dribbble: "https://dribbble.com/MrSaints"
    github: "https://github.com/MrSaints"
    twitter: "https://twitter.com/MrSaints"
gems:
    - jekyll-redirect-from